// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKg9NLh78jjthMN7EDFpyiu4La6KWx1JY',
    appId: '1:156514679388:web:52f154cc82da9f09924499',
    messagingSenderId: '156514679388',
    projectId: 'improsso-700aa',
    authDomain: 'improsso-700aa.firebaseapp.com',
    storageBucket: 'improsso-700aa.appspot.com',
    measurementId: 'G-6DRFTR3GCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubTgZT8nqtFxjmRvdROUms5ot67TuFo8',
    appId: '1:156514679388:android:cdfc32a362168a1b924499',
    messagingSenderId: '156514679388',
    projectId: 'improsso-700aa',
    storageBucket: 'improsso-700aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICSDwUYkeQAFmiCJ5QwjoJnjUaXBn9qQ',
    appId: '1:156514679388:ios:437ebb311e2a2c59924499',
    messagingSenderId: '156514679388',
    projectId: 'improsso-700aa',
    storageBucket: 'improsso-700aa.appspot.com',
    iosClientId: '156514679388-uf5vqj31li30afdo1fpqnt766v2b00cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.improsso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICSDwUYkeQAFmiCJ5QwjoJnjUaXBn9qQ',
    appId: '1:156514679388:ios:437ebb311e2a2c59924499',
    messagingSenderId: '156514679388',
    projectId: 'improsso-700aa',
    storageBucket: 'improsso-700aa.appspot.com',
    iosClientId: '156514679388-uf5vqj31li30afdo1fpqnt766v2b00cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.improsso',
  );
}
